# Generated by Django 5.0.3 on 2024-03-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('ultimoIngreso', models.DateField()),
                ('ultimoPago', models.DateField()),
                ('venceCuota', models.DateField()),
            ],
        ),
    ]
