# Generated by Django 5.0.3 on 2024-03-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultimoIngreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimoPago',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='venceCuota',
            field=models.DateField(null=True),
        ),
    ]
