# Generated by Django 5.0.3 on 2024-03-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_alter_usuario_ultimoingreso_alter_usuario_ultimopago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultimoIngreso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimoPago',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='venceCuota',
            field=models.DateTimeField(null=True),
        ),
    ]
